name: Go
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go modules cache
        id: cache-go-module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - name: Setup Go build cache
        id: cache-go-build
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-gobuild-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gobuild-

      - name: Download dependencies
        if: steps.cache-go-module.outputs.cache-hit != 'true'
        run: go mod download

      - name: Verify go modules up to date
        run: |
          set -ex
          go mod tidy
          [ -z "$(git diff -- go.{mod,sum})" ] # Check there are no changes!

      - name: Test
        run: go test -race ./...

      # Run golangci-lint in same job as tests as the golangci-lint task can not
      # resolve private dependencies.
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          skip-go-installation: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: false
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=10m
